### ISSUE TITLE
Support Arrays

### ISSUE THREAD

**Issue by lmiol** [mehimanshupatil/propertiesToJSON#1]
```
multiDimArray[0][0]=00
multiDimArray[0][1]=01
multiDimArray[1][0]=10
multiDimArray[1][1]=11
```

to
```
{
 "multiDimArray": [
    [
      "00",
      "01"
    ],
    [
      "10",
      "11"
    ]
  ]
  }
```

And

```
cost.multiDimArray[0][0]=00
cost.multiDimArray[0][1]=01
cost.multiDimArray[1][0]=10
cost.multiDimArray[1][1]=11
```

to

```
{
"cost": {
"multiDimArray": [
[
"00",
"01"
],
[
"10",
"11"
]
]
}
}
  
```

**Comment by lmiol** [comment]
cost.multiDimArray[0][0]=00
cost.multiDimArray[0][1]=01
cost.multiDimArray[1][0]=10
cost.multiDimArray[1][1]=11

to

{
  "cost": {
"multiDimArray": [
[
"00",
"01"
],
[
"10",
"11"
]
]
}

**Comment by mehimanshupatil** [comment]
I am working on the same. If you have workaround you can share it

**Comment by mehimanshupatil** [comment]
@lmiol have added support for array please check

**Comment by lmiol** [comment]
Sorry for long responce
i have tested. Works brilliant!
